services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:3000/api/v1
    ports:
      - "3001:5173"
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - PORT=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - type: bind
        source: ./server
        target: /app
        consistency: cached
      - /app/node_modules
