services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:3000/api/v1
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://mongodb:27017/meal-plan

  mongodb:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=meal-plan

volumes:
  mongodb_data:
